#!/usr/bin/env python3

import os
import shutil
import logging


LOGGING_FILE="/home/adityas/Logs/clearer.log"

logging.basicConfig(format="%(asctime)s : %(levelname)s - %(message)s",level=logging.DEBUG,filename=LOGGING_FILE)

logging.info("Deleting trash.")
ROOT_DIR="/home/adityas/Trash"
logging
files=os.listdir(ROOT_DIR)
absolute_files=map(lambda x:ROOT_DIR+"/"+x,files)
for _file in list(absolute_files):
    logging.info("Deleting %s"%(str(_file)))
    if os.path.isfile(_file):
        os.remove(_file)
    elif os.path.isdir(_file):
        shutil.rmtree(_file)
    else:
        logging.error("While deleting %s"%(str(_file)))
logging.info("Done deleting trash.")
